/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coroutines

class CoroutineApp {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(CoroutineApp().greeting)
}
