/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coroutines

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = CoroutineApp()
        println("hello, I am testing CoroutineApp")
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
